# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
# Code here
import numpy as np

In [7]:
A = np.array([[1402,191],[1371,821],[949,1437],[147,1448]])
B = np.array([[1,2,3],[4,5,6]])

In [10]:
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [11]:
# Code here
print(A.shape,B.shape)

(4, 2) (2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [13]:
# Code here
print(A[0][0])
print(A[0][1])
print(A[2][1])
print(A[3][0])

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [58]:
# Code here
matrix = np.zeros((3,3))
scalar = matrix[0][0]

In [71]:
for x in range(3):
    for y in range(3):
        matrix[x][y] = np.random.randint(1,10)
    

In [72]:
matrix

array([[5., 6., 8.],
       [8., 4., 9.],
       [3., 8., 8.]])

In [73]:
matrix

array([[5., 6., 8.],
       [8., 4., 9.],
       [3., 8., 8.]])

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [79]:
# Code here
def matrix_function(x,y):
    matrix1 = np.zeros((x,y))
    matrix2 = np.zeros((x,y))
    
    for x in range(3):
        for y in range(3):
            matrix1[x][y] = np.random.randint(1,10)
            matrix2[x][y] = np.random.randint(1,10)
#     print(matrix1)
#     print(matrix2)
    return matrix1+matrix2

In [78]:
matrix_function(4,4)

[[3. 6. 4. 0.]
 [3. 5. 1. 0.]
 [9. 5. 7. 0.]
 [0. 0. 0. 0.]]
[[6. 1. 7. 0.]
 [7. 9. 1. 0.]
 [2. 5. 6. 0.]
 [0. 0. 0. 0.]]


array([[ 9.,  7., 11.,  0.],
       [10., 14.,  2.,  0.],
       [11., 10., 13.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  